export const MyProfile = () => {
    return (
        <div>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
            <h1>My Profile</h1>
        </div>
    );
};

export default MyProfile;
