export { default as Home } from './home';
export { default as About } from './about';
export { default as Contact } from './contact';
export { default as Login } from './auth/login';
export { default as SignUp } from './auth/signup';
export { default as Verify } from './auth/verify';
export { default as NewPassword } from './auth/new-password';
export { default as ResetPassword } from './auth/reset-password';
export { default as NotFound } from './not-found';
